UNR-237: Replace unknown RPC check with error message
spatialos/UnrealGDK pull request #108
Opened 2018-05-21 18:40 UTC by m-samiec

Output error message when attempting to call unknown RPC instead of asserting.

Primary reviewers: @girayimprobable @joshuahuburn

2018-05-21 18:42 UTC, girayozil requested changes

2018-05-21 18:53 UTC, girayozil approved these changes
One change recommended, but not necessary.

2018-05-21 20:18 UTC, joshuahuburn approved these changes
LGTM

2018-05-22 08:56 UTC, danielimprobable approved these changes
LGTM

2018-05-22 10:27 UTC, merged