UNR-188 - RPC ownership fix
spatialos/UnrealGDK pull request #229
Opened 2018-07-27 13:50 UTC by mpmisko

#### Description

Clients can send Server RPCs even if they don't have ownership.  This PR fixes this behavior by checking the `getNetConnection()` of the actors. If the connection is not present, then we can safely disregard the RPC and fail. 

#### Tests

There are two cases that I have tested. First, when the object we are calling an RPC on is just a simple `Pawn`. Second, when it is an `Actor` controlled by a different client. In both cases, the RPC fails to send just as in native Unreal. Also, this is the same way disregarding these RPCs is implemented in native Unreal.

#### Primary reviewers
@improbable-valentyn @danielimprobable 

Ticket link: https://improbableio.atlassian.net/browse/UNR-188

2018-07-27 14:30 UTC, wanqizhu approved these changes
LGTM. Did not reproduce test but traced through logic of 4 different cases for serverRPC as per https://docs.unrealengine.com/en-us/Gameplay/Networking/Actors/RPCs and seem to cover all cases.

2018-07-27 14:59 UTC, improbable-valy approved these changes

2018-07-27 19:29 UTC, girayozil requested changes
Please see the comments added by Sahil and me.

2018-07-30 10:56 UTC, danielimprobable approved these changes

2018-07-30 14:22 UTC, girayozil approved these changes

2018-07-30 15:33 UTC, Vatyx approved these changes

2018-07-30 16:08 UTC, merged