Update premerge.steps.yaml
spatialos/UnrealGDK pull request #3043
Opened 2021-04-20 16:05 UTC by simonsarginson

2021-04-20 16:09 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        ENGINE_BRANCH: "4.26-SpatialOSUnrealGDK-0.13.0-rc"
```suggestion
        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
        ENGINE_BRANCH: "4.26-SpatialOSUnrealGDK-0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```

2021-04-20 16:10 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        PROJECT_BRANCH: "0.13.0-rc"
```suggestion
        PROJECT_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```

2021-04-20 16:10 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK-0.13.0-rc"
```suggestion
        GDK_BRANCH: "0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK-0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
```

2021-04-20 16:10 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        PROJECT_BRANCH: "0.13.0-rc"
```suggestion
        PROJECT_BRANCH: "0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
```

2021-04-20 16:27 UTC, mironec commented on .buildkite/premerge.steps.yaml
> +        GDK_BRANCH: "0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
```suggestion
        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```
and elsewhere

2021-04-20 16:41 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK-0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
```suggestion
        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK-0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```

2021-04-20 16:41 UTC, simonsarginson commented on .buildkite/premerge.steps.yaml
> +        PROJECT_BRANCH: "0.13.0-rc" " # NOTE: temp fix for new ci release interop issues
```suggestion
        PROJECT_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```

2021-04-21 10:04 UTC, mironec commented on .buildkite/premerge.steps.yaml
> +        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
Ah, this one should stay `${BUILDKITE_BRANCH}`, otherwise PRs into 0.13.0-rc will be running as 0.13 instead of themselves.

2021-04-21 10:04 UTC, mironec commented on .buildkite/premerge.steps.yaml
> +        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
similar here: `${BUILDKITE_BRANCH}`

2021-04-21 10:15 UTC, joshuahuburn requested changes

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
```

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        ENGINE_BRANCH: "4.26-SpatialOSUnrealGDK-0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        ENGINE_BRANCH: "${ENGINE_BRANCH:-4.26-SpatialOSUnrealGDK-0.13.0-rc}" # NOTE: temp fix for new ci release interop issues
```

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        PROJECT_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        PROJECT_BRANCH: "${PROJECT_BRANCH:-0.13.0-rc}" # NOTE: temp fix for new ci release interop issues
```

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        GDK_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
```

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK-0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        ENGINE_BRANCH: "${ENGINE_BRANCH:-4.25-SpatialOSUnrealGDK-0.13.0-rc}" # NOTE: temp fix for new ci release interop issues
```

2021-04-21 10:15 UTC, joshuahuburn commented on .buildkite/premerge.steps.yaml
> +        PROJECT_BRANCH: "0.13.0-rc" # NOTE: temp fix for new ci release interop issues
```suggestion
        PROJECT_BRANCH: "${PROJECT_BRANCH:-0.13.0-rc}" # NOTE: temp fix for new ci release interop issues
```

2021-04-21 10:48 UTC, joshuahuburn approved these changes

2021-04-21 10:53 UTC, mironec approved these changes

2021-04-21 10:54 UTC, mironec approved these changes

2021-04-21 10:56 UTC, merged