Add remote insights enabling
spatialos/UnrealGDK pull request #3134
Opened 2021-05-20 14:37 UTC by m-samiec

#### Description
Added `SpatialExecServerCmd` console command with one command `StartInsights` to dynamically enable insights capturing.
Engine PR: https://github.com/improbableio/UnrealEngine/pull/932

Usage:
SpatialExecServerCmd < server > < command > < args >

Flow of events;
On execution the client validates that the command is a known valid command otherwise errors and returns.
The valid command is then sent via the client's player controller to the client's owning server.
The owning server parses the < server > argument to determine the destination server for the command.
- < server > can be "local" and will be executed directly on the client's owning server.
- < server > can also be the server worker name (eg. "UnrealWorker1398FEE345526D0B9EFC52BA7F5C094F").
- If < server > is not matched to an existing server, an error is output and the command is aborted.

Once the command is on the correct server, the individual command can be executed (the only valid command currently is `StartInsights`).
StartInsights passes <args> through to the Trace tool which parses the < args > in the same manner it would starting command line arguments.

Example usage:
SpatialExecServerCmd local StartInsights -trace=CustomChannel -tracefile=MyNewTrace 

If a trace is already active either via the command line launch arguments, or a previous call to "StartInsights", then the command is ignored.

#### Release note
Added

#### Primary reviewers
@improbable-danny @cmsmithio @martin-improbable

2021-05-20 15:08 UTC, cmsmithio commented
Looks great Mike, any chance we will run into issues with log file name collisions if we turn this on for multiple servers?

2021-05-20 15:09 UTC, cmsmithio reviewed
just one comment/question posted

2021-05-20 16:37 UTC, cmsmithio commented
> Looks great Mike, how hard do you think it would be to autogen the log names from the worker name?

Mike and I discussed this, sounds like it will autogenerate a log name in the case it is omitted.

2021-05-20 17:04 UTC, m-samiec commented
> > Looks great Mike, how hard do you think it would be to autogen the log names from the worker name?
> 
> Mike and I discussed this, sounds like it will autogenerate a log name in the case it is omitted.

Yes in the case it's omitted (eg. "-tracefile=") it generates a filename from the date-time - FDateTime::Now().ToString(TEXT("%Y%m%d_%H%M%S.utrace"))

2021-05-21 08:04 UTC, martin-improbable requested changes
A few minor things, apart from that it looks very good!

2021-05-21 13:40 UTC, m-samiec commented on SpatialGDK/Source/SpatialGDK/Private/Interop/DebugMetricsSystem.cpp
> +				}
There's another commands on the server worker entity that get handled elsewhere - SpatialPlayerSpawner and the forward_spawn_player command

2021-05-24 08:11 UTC, martin-improbable approved these changes

2021-05-24 13:55 UTC, improbable-danny commented on SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
> +const EServerCommands ServerCommandsStringToEnum(const FString& Command)
This functionality can be provided by UENUM but would require ServerCommandInvalid to be it's own value I think

2021-05-24 13:57 UTC, improbable-danny commented on SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
> +const EServerCommands ServerCommandsStringToEnum(const FString& Command)
Think I might be misremembering this..

2021-05-24 14:00 UTC, improbable-danny commented on SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp
> +const EServerCommands ServerCommandsStringToEnum(const FString& Command)
Ah you can do EnumToString but StringToEnum is just a loop/cmp over EnumToString(i) = String

2021-05-26 09:05 UTC, improbable-danny approved these changes

2021-05-26 23:02 UTC, merged