[UNR-95] - User defined classes and header includes via .ini file.
spatialos/UnrealGDK pull request #86
Opened 2018-04-27 14:13 UTC by joshuahuburn

What?
Threw together a solution for the .ini file idea specified in :https://docs.google.com/document/d/1ucVykJFN5dDTTrSrcRgmqI3F7wRKb5yt4pZQR4c3cSk/edit#heading=h.bdey6ri4av70

https://improbableio.atlassian.net/browse/UNR-95

How?
Using Unreal's ini file handling we just parse the "DefaultEditorSpatialGDK.ini" and get the section "UserInteropCodeGenSettings". Here we have defined class names and associated headers, see SampleGame PR: 
https://github.com/improbable/unreal-gdk-sample-game/pull/14

Tested?
Works exactly the same as the hard-coded version but now you can just edit the ini file whenever you want :D

2018-04-27 14:46 UTC, m-samiec requested changes
Few small changes, but looks good overall!

2018-04-27 16:49 UTC, joshuahuburn reviewed
Reviewed changes, PTAL.

2018-04-27 17:07 UTC, m-samiec approved these changes

2018-04-30 10:28 UTC, joshuahuburn reviewed
Changes addressed.

2018-04-30 12:57 UTC, improbable-valy approved these changes

2018-04-30 13:16 UTC, merged